from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.db.session import get_db
from app.models.chat_message import ChatMessage
from app.schemas.chat import ChatMessageRead, ChatRequest, ChatResponse
from app.services.ai_client import ai_client
from app.services.patient_service import get_patient_by_patient_id

router = APIRouter(prefix="/patients/{patient_id}/chat", tags=["chat"])


@router.post("", response_model=ChatResponse)
def chat_with_patient(patient_id: str, request: ChatRequest, db: Session = Depends(get_db)):
    patient = get_patient_by_patient_id(db, patient_id)
    if not patient:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Patient not found.")

    answer, source = ai_client.chat_with_patient_context(db, patient, request.question)
    if source == "remote_ai":
        note = "Answer generated by the remote AI service using the saved patient context. This is educational support only, not a final diagnosis."
    else:
        note = "Answer generated locally from the saved patient context. This is educational support only, not a final diagnosis."
    return ChatResponse(answer=answer, note=note, source=source)


@router.get("/history", response_model=list[ChatMessageRead])
def get_chat_history(patient_id: str, db: Session = Depends(get_db)):
    patient = get_patient_by_patient_id(db, patient_id)
    if not patient:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Patient not found.")

    return (
        db.query(ChatMessage)
        .filter(ChatMessage.patient_db_id == patient.id)
        .order_by(ChatMessage.created_at.asc())
        .all()
    )
